security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email  # Utiliser "email" ou "pseudo" en fonction de votre champ d'identifiant

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: app_connexion          # Route d'affichage du formulaire de connexion
        check_path: app_connexion          # Route de soumission du formulaire
        username_parameter: connexion_form[email]        # Nom du champ pour l'email (ou pseudo selon votre cas)
        password_parameter: connexion_form[password]      # Nom du champ pour le mot de passe
        default_target_path: /profil       # Page de redirection après connexion réussie

      logout:
        path: app_logout                   # Route pour se déconnecter
        target: app_connexion              # Page vers laquelle rediriger après déconnexion

  access_control:
    # - { path: ^/profil, roles: ROLE_USER } # Accès à la page profil pour les utilisateurs connectés
    # Ajoutez d'autres règles ici pour les autres pages si besoin

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4        # Valeur la plus basse pour bcrypt
        time_cost: 3   # Valeur la plus basse pour argon
        memory_cost: 10 # Valeur la plus basse pour argon
